name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRUEBAS_TIENDA_17949 }}'
          projectId: 'pruebas-tienda-17949'
          channelId: 'live'   # despliega al canal de producción
